### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Vjacheslav250/kinozal-verstka-na-Bootstrap#1]
скругления отсуствуют
![image](https://user-images.githubusercontent.com/8464662/127890512-16137243-30e8-4007-b3f1-7b2861e7eb83.png)

**Comment by Vjacheslav250** [comment]
Добрый день, Андрей!
Исправил, добавил скругления!

**Comment by Vjacheslav250** [comment]
https://vjacheslav250.github.io/kinozal-verstka-na-Bootstrap/page.html

**Comment by Alecto** [comment]
отлично, работа принята

пт, 6 авг. 2021 г. в 11:13, Вячеслав Пометун ***@***.***>:

**Comment by Vjacheslav250** [comment]
Спасибо!
